### ISSUE TITLE
Doesnt account for special events

### ISSUE THREAD

**Issue by Erix-glitch** [didlly/grank#14]
**Is your feature request related to a problem? Please describe.**
Whenever there is a special event (see picture), the command your using (in this case, fishing rod) will break.
![image](https://user-images.githubusercontent.com/71719838/153517614-d7e0862f-9b2f-4274-901a-07467f599fcf.png)

**Describe the solution you'd like**
Add code to account for these events and interact to them

**Comment by Erix-glitch** [comment]
btw its green because i manually interacted

**Comment by didlly** [comment]
This bug will be fixed soon once more features have been added.

**Comment by didlly** [comment]
This is being worked on now.

**Comment by didlly** [comment]
Added in [this](https://github.com/didlly/grank/commit/c3ecb71f360145646f84a7d656834beac7036bb2) commit.
