### ISSUE TITLE
Multi-instancing not working?

### ISSUE THREAD

**Issue by KC080** [didlly/grank#16]
I have entered  the token and channel_id values into credentials.json, but when I run main.py it says this. Note this error doesn't occur when using one token and one channel_id.

![image](https://user-images.githubusercontent.com/77486627/155704190-2a156503-2667-4ffb-a11a-7b254a814a51.png)

This is my credentials.json file:

{
   "tokens": ["insertfaketokenhere", "insertfaketokenhere"],
   "channel_ids": [946390368147083394, 946722936545509396]
}

**Comment by didlly** [comment]
Hey @KC080,

Good catch. ~~I guess that's what I get for not testing updates with multiple tokens.~~Fixed in [this](https://github.com/didlly/grank/commit/4df2eb9ca97aa04545f310eba1cc53607c5341fb) commit.
