### ISSUE TITLE
Dank Memer April rewrite

### ISSUE THREAD

**Issue by jinja365** [didlly/grank#18]
So the dank memer devs just said that they were going to rewrite their bot to switch from 'pls beg' to '/currency beg' aka slash commands
and since slash commands dont work the same way and i dont think their is a 'send slash command' endpoint just like there is for 'send message' endpoint
this will completely break grank and dankgrinder 
Im just informing so that you can make the neccesary changes early on( if its even possible to use slash cmds via http requests) and since your making a lot of changes and new features and i dont want them to go to waste :)
Thanks!

**Comment by didlly** [comment]
Thanks @jinja365,

I'll have a look into this.

**Comment by jinja365** [comment]
Alr good luck
btw there is a library called discum and it is basically for selfbotting aka its a discord.py version for selfbots
https://github.com/Merubokkusu/Discord-S.C.U.M
this library is soo cool because it supports 'using'/sending slash commands as shown [here](https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/examples/slashcommands.py)
so you could make use of this library and if you could fit the multi instancing feature into this then it will soo good dude

but we still have an issue
if dank memer switches to slash commands , then most messages will be in the ephemeral format
but according to [this](https://github.com/discord/discord-api-docs/discussions/3291#discussioncomment-1023345) command on the discord api docs github, ephemeral messages arent stored so your current method of retrieving messages as seen in discord/message.py would not work ( i suppose) as that endpoint retrieves message sent in the channel and i dont think ephemeral messages count as they arent stored as mentioned above

i hope you can figure it out

**Comment by didlly** [comment]
Hey @jinja365,

I have worked out how you can send slash commands through Discord's API. It is a post request to `https://discord.com/api/v9/interactions`. Here is an example payload that will initiate Dank Memer's `/8ball` slash command. The fields which are empty with comments after them contain data I would like to keep private.

```json
{
  "type": 2,
  "application_id": "270904126974590976",
  "guild_id": "", # ID of the guild the slash command should be sent in. This can be got in the returned payload from retreiving a message from a channel.
  "channel_id": "", # ID of the channel the slash command should be sent in. This will be got from the user.
  "session_id": "", # One of you possibly multiple session IDs. This will be got from the Websocket READY event (https://github.com/didlly/grank/blob/main/src/discord/gateway.py)
  "data": {
    "version": "1", # According to Discord's docs (https://discord.com/developers/docs/interactions/receiving-and-responding#interactions) this should be 1.
    "id": "824708968777646100", # Specific ID of the interaction.
    "name": "8ball", # Name of the interaction
    "type": 1, # Interaction type. Type 1 accoring to Discord's docs (https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-type) is called `PING`.
    "options": [ # List of options and their arguments.
      {
        "type": 3, # Interaction type. Type 3 accoring to Discord's docs (https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-type) is called `MESSAGE_COMPONENT`.
        "name": "question", # Name of the argument that is being passed in this dict.
        "value": "test" # Value of the argument.
      }
    ],
    "application_command": {
      "version": "824708968777646101", # According to Discord's docs `autoincrementing version identifier updated during substantial record changes' (https://discord.com/developers/docs/interactions/application-commands#application-commands)
      "type": 1, # Type of command, in this case it is `CHAT_INPUT` -  (https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-types)
      "permissions": [],
      "options": [
        {
          "type": 3, # Options type - in this case string (https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type)
          "required": true,
          "name": "question",
          "description": "The question you want to ask the magic 8ball"
        }
      ],
      "name": "8ball",
      "listed": true,
      "id": "824708968777646100", # Unique ID of the slash command.
      "dm_permission": null,
      "description": "Ask the magic 8ball a question",
      "default_permission": true,
      "default_member_permissions": null,
      "application_id": "270904126974590976" # The bot's (in this case Dank Memer's) ID.
    },
    "attachments": []
  },
  "nonce": "947463516342714368" # Timestamp of the message. Optional (won't be send when Grank is updated).
}
```

**Comment by jinja365** [comment]
Nice man!
Good luck with developement!

**Comment by didlly** [comment]
Thanks.

**Comment by jinja365** [comment]
uh i have a question
you passed in the 'unique id' of the slash cmd
do u get this id from the information in the network tab when using a slash command?

**Comment by didlly** [comment]
> uh i have a question you passed in the 'unique id' of the slash cmd do u get this id from the information in the network tab when using a slash command?

It can be found there. When a bot registers a slash command, it is given a unique id.

**Comment by jinja365** [comment]
Alr GL
