### ISSUE TITLE
Certain Trivia Questions don't get Answered

### ISSUE THREAD

**Issue by smintf** [didlly/grank#23]
**Describe the bug**
Certain `pls trivia` questions don't get answered correctly even though they exist in the database.json file.

**Expected behavior**
The `pls trivia` questions get answered correctly as they exist in the database.json file.

**Screenshots**
[Terminal Output](https://nothing-to-see-he.re/5qXWG99gW)
[Discord](https://nothing-to-see-he.re/5qXWCqjyn)
[database.json](https://nothing-to-see-he.re/5qXWHdfkX)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.2

**Additional context**
I assume it is caused by the special characters that these questions have (eg: &/`&amp;`)

**Comment by didlly** [comment]
Fixed in [this](https://github.com/didlly/grank/commit/da57784e04fda491284606d86c50536dd071d466) commit.
