### ISSUE TITLE
'channel ids' key missing when run from source.

### ISSUE THREAD

**Issue by smintf** [didlly/grank#26]
**Describe the bug**
Grank fails to load because it cannot find the `channel ids` key.

**Expected behavior**
Grank loads properly.

**Screenshots**
[Terminal Output](https://nothing-to-see-he.re/5r2HZLqYk)
[credentials.json (from source)](https://nothing-to-see-he.re/5r2I8lixs)

**Desktop**
 - OS: Windows
 - Version: 1.4.1 (Running from Source)

**Additional context**
Caused by typo in `credentials.json` (`channel ids` being spelled as `channel_ids`)

**Comment by didlly** [comment]
Fixed in [this](https://github.com/didlly/grank/commit/b69bd346ffcdf40a38695f9a308705acbd092fe7) commit.
