### ISSUE TITLE
Unknown Trivia Question Error for Questions with the String "Pokémon"

### ISSUE THREAD

**Issue by smintf** [didlly/grank#29]
**Describe the bug**
Trivia Questions with the String `Pokémon` don't get answered and Grank throws a warning, even though the Questions exist in [`database.json`](https://github.com/didlly/grank/blob/main/src/database.json).

**Expected behavior**
These Trivia Questions get answered as they exist in [`database.json`](https://github.com/didlly/grank/blob/main/src/database.json).

**Screenshots**
[Terminal Output](https://nothing-to-see-he.re/5r8SdcAC5)
[Discord](https://nothing-to-see-he.re/5r8QPl8Rh)
[database.json](https://nothing-to-see-he.re/5r8QxevM0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.6

**Additional context**
Perhaps caused by the `é` character present in them???

**Comment by didlly** [comment]
Fixed.
