### ISSUE TITLE
Server Termed?

### ISSUE THREAD

**Issue by Wick9999** [didlly/grank#32]
If yes then pls make a new one

**Comment by didlly** [comment]
I think someone hacked my Discord account...

**Comment by Wick9999** [comment]
> I think someone hacked my Discord account...

Disable the account and make new one ig

**Comment by SoulHunter287** [comment]
didlly disable your account wait for 2 minutes 
again login the acc and then change the pass and add 2fa

**Comment by didlly** [comment]
Discord is requesting phone verification, and I currently don't have access to a phone. I am currently working with Discord support to get back in to my account.

**Comment by Vamshi2004nice** [comment]
Oh carry on buddy

**Comment by SoulHunter287** [comment]
Discord support is trash

**Comment by Wick9999** [comment]
> Discord support is trash
yea

**Comment by SoulHunter287** [comment]
didlly got ur acc back ?

**Comment by Zyzy69** [comment]
I can help you with a temp number site, it will allow you to use a one time use code for phone verification

**Comment by didlly** [comment]
> I can help you with a temp number site, it will allow you to use a one time use code for phone verification

Go ahead...

**Comment by SoulHunter287** [comment]
> I can help you with a temp number site, it will allow you to use a one time use code for phone verification

Ayoo which website

**Comment by Wick9999** [comment]
didly u can make alt till discord resolves the issue (usually they do not care) so yeah maybe this or u can use a temp no. as Zyzy69 said above this two are the only possible ways

**Comment by Zyzy69** [comment]
> > I can help you with a temp number site, it will allow you to use a one time use code for phone verification
> 
> Go ahead...

Well when you're ready, I give you a number and then I give you the OTP to verify it.

**Comment by SL4F** [comment]
https://smspva.com

**Comment by jinja365** [comment]
btw is a replit version of grank out?

**Comment by didlly** [comment]
> btw is a replit version of grank out?

https://replit.com/@didlly/grank

### Env vars
Add a env var called `token` containing your token.

**Comment by smintf** [comment]
> I think someone hacked my Discord account...

Create a new one for the time being?

**Comment by didlly** [comment]
Here: https://discord.gg/X3JMC9FAgy

**Comment by Nostorian** [comment]
> https://smspva.com Legit I’ve used it

bruh what, that shit works?
