### ISSUE TITLE
Improvements 

### ISSUE THREAD

**Issue by Wick9999** [didlly/grank#33]
1. I always have to come every 30-40 mins to reactivate horsheshoe , pizza , tidepod etc so it would be really helpful if it automatically uses hoes,pizza,pods and dailys.
 
 2. new cmd req - pls bet and pls pet.
 
 3. Shifts dont work so the bot runs 24/7 which might result in ban/blacklist. (replit version)
 
 These are some things that i think can be implemented in a future update but even without these the bot is super good thanks dildy for making it!

**Comment by didlly** [comment]
> 1. I always have to come every 30-40 mins to reactivate horsheshoe , pizza , tidepod etc so it would be really helpful if it automatically uses hoes,pizza,pods and dailys.
> 
>     2. new cmd req - pls bet and pls pet.
> 
>     3. Shifts dont work so the bot runs 24/7 which might result in ban/blacklist. (replit version)
> 
> 
> These are some things that i think can be implemented in a future update but even without these the bot is super good thanks dildy for making it!

For Point 1, custom commands.
For Point 2, noted.
For Point 3, noted aswell.

**Comment by didlly** [comment]
@Wick9999 Also, shifts work fine for me. Can you make sure you enabled them in the config? Try smaller active and passive phases to check it works.
