### ISSUE TITLE
Forking

### ISSUE THREAD

**Issue by DscNLg** [didlly/grank#34]
Need the forking enabled though

**Comment by didlly** [comment]
You can fork the repository. What do you mean?

**Comment by DscNLg** [comment]
![image](https://user-images.githubusercontent.com/102135624/163519730-d803138a-f997-4a48-aa6d-77a764b077bb.png)

**Comment by didlly** [comment]
@DscNLg Can you send a friend to my Discord account (didlly#0302) please. Also, other people have forked this repository after you filed this issue so I am not sure why you can't fork it.
