### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Renaissance96** [didlly/grank#38]
i need help with following things :
1. custom command cooldown not working, it keeps on spamming same command again and again.
2. there is no web for getting repl link to host on uptime robot, you can try it yourself.
3. when we change shifts to True, farmer stops working, and when its false it works.

**Comment by didlly** [comment]
Make sure you are using the latest version of Grank.

1) Custom commands work for me, can anyone else comment whether custom commands work for them.
2) What do you mean? The repl link is https://replit.com/@didlly/Grank. Just use Freshping.
3) That means shifts are working. Shifts work by making the farmer run for the specified amount of seconds, and sleep for the specified amount of seconds. This process repeats.

**Comment by Renaissance96** [comment]
Yes i am using the latest version.

1. custom commands working but it keeps on spamming same command again and again every second.
2. ok i will use freshping instead of uptime robot.
3. so first it will be inactive for a period of time and then active after dormant time is over?
also if you have a discord account or server for assistance, it will be really good.

**Comment by didlly** [comment]
> Yes i am using the latest version.
> 
> 1. custom commands working but it keeps on spamming same command again and again every second.
> 2. ok i will use freshping instead of uptime robot.
> 3. so first it will be inactive for a period of time and then active after dormant time is over?
> also if you have a discord account or server for assistance, it will be really good.

3)  I had one but my Discord account got hacked.

**Comment by Renaissance96** [comment]
you can create another account or if you say i can make one for you and give login details here.

**Comment by Gudd12** [comment]
I can also help you homie with my alts if you want . Also the latest version of Frank has a error like : 
1. It works fine if you use your browser but if one token is connected with the desktop discord app and another with web than the web one runs fine but the desktop one does not run . I will also post what error it gives . 
Btw this is the best dank grinder I have ever used 
Ur a nice dev 😉

**Comment by Renaissance96** [comment]
> I can also help you homie with my alts if you want . Also the latest version of Frank has a error like :
> 
> 1. It works fine if you use your browser but if one token is connected with the desktop discord app and another with web than the web one runs fine but the desktop one does not run . I will also post what error it gives .
>    Btw this is the best dank grinder I have ever used
>    Ur a nice dev 😉

can i have your discord tag?

**Comment by Gudd12** [comment]
> 

U mean auth token or id ? Btw are you one of the Dev's . Anyways it's my alt so np .

**Comment by Gudd12** [comment]
> > I can also help you homie with my alts if you want . Also the latest version of Frank has a error like :
> > 
> > 1. It works fine if you use your browser but if one token is connected with the desktop discord app and another with web than the web one runs fine but the desktop one does not run . I will also post what error it gives .
> >    Btw this is the best dank grinder I have ever used
> >    Ur a nice dev 😉
> 
> can i have your discord tag?
Homie the repllit version of this does not work

**Comment by Renaissance96** [comment]
its workimg for me.

**Comment by Gudd12** [comment]
Oh idk bro it keeps saying invalid token

**Comment by Gudd12** [comment]
Can u gimme the latest Frank link

**Comment by Renaissance96** [comment]
https://replit.com/@didlly/Grank

**Comment by Gudd12** [comment]
Okie

**Comment by Gudd12** [comment]
Thx

**Comment by Renaissance96** [comment]
![Screenshot_2022-04-22-16-23-32-70](https://user-images.githubusercontent.com/60173156/164701335-351fa040-afa3-4ad4-96f9-086651c365ec.jpg)

**Comment by Renaissance96** [comment]
1. in custom command when we use time 1 hour, it is still sending command at every 300s.
2. shift should be True right for stopping and activating it automatically after a period of time?

**Comment by Gudd12** [comment]
Can I do pls bet in custom cmds too ?

**Comment by Gudd12** [comment]
> 1. in custom command when we use time 1 hour, it is still sending command at every 300s.
> 2. shift should be True right for stopping and activating it automatically after a period of time?

Can I have yo discord I'd than we talk cos me have some issues ;-;

**Comment by Gudd12** [comment]
> i need help with following things :
> 
> 1. custom command cooldown not working, it keeps on spamming same command again and again.
> 2. there is no web for getting repl link to host on uptime robot, you can try it yourself.
> 3. when we change shifts to True, farmer stops working, and when its false it works.

Same thing wth me

**Comment by Gudd12** [comment]
![Screenshot_2022-04-22-19-26-25-831_com android chrome](https://user-images.githubusercontent.com/103954053/164729072-193958e0-f4b1-46df-a996-d10671f54ff5.jpg)
See i am having issues using the Mobile version of grank. I had put all the token channel IDs still

**Comment by didlly** [comment]
> Can I do pls bet in custom cmds too ?

Yes

**Comment by didlly** [comment]
> 1. in custom command when we use time 1 hour, it is still sending command at every 300s.
> 2. shift should be True right for stopping and activating it automatically after a period of time?

1) I found the bug, it was caused by me forgetting to make Grank set the last run of the custom command. I am just polishing of the bug fix.
2) Yes.

**Comment by didlly** [comment]
> shifts still not working 

They are - check closed issue number #33

**Comment by didlly** [comment]
I havent updated the repl yet though

**Comment by Renaissance96** [comment]
> > shifts still not working
> 
> They are - check closed issue number #33

the problem is whenever i change shift to "True" it does not work anymore.
![Screenshot_2022-04-22-21-44-09-15](https://user-images.githubusercontent.com/60173156/164753954-16723ccb-20f5-42af-8152-83fccd96c67a.jpg)
![Uploading Screenshot_2022-04-22-21-44-28-49.jpg…]()

**Comment by Renaissance96** [comment]
![Uploading Screenshot_2022-04-22-21-44-28-49.jpg…]()

**Comment by Renaissance96** [comment]
![Screenshot_2022-04-22-21-47-54-23](https://user-images.githubusercontent.com/60173156/164754459-1c652bea-8040-4e9f-acd8-76dc9d26b879.jpg)

**Comment by Renaissance96** [comment]
Also as you can see in screenshot, there is no web on right side on console for getting the link and hosting it on uptime robot and freshping. maybe you can test yourself and ty for all the assistance.
![Screenshot_2022-04-22-21-51-24-38](https://user-images.githubusercontent.com/60173156/164754989-a8210cc9-d388-42c2-b1fb-ca7c07831430.jpg)

**Comment by didlly** [comment]
> Also as you can see in screenshot, there is no web on right side on console like this one in the ss for getting the link and hosting it on uptime robot and freshping. maybe you can test yourself and ty for all the assistance.
> ![Screenshot_2022-04-22-21-51-24-38](https://user-images.githubusercontent.com/60173156/164754989-a8210cc9-d388-42c2-b1fb-ca7c07831430.jpg)
> 

Like I said, the repl hasn't been updated to the latest version yet.

**Comment by Renaissance96** [comment]
ah kk
hope you will update it soon.

**Comment by Renaissance96** [comment]
when the new repl version will be released?

**Comment by Gudd12** [comment]
> put token in environment and not in configuration. create a variable in environment and name it "token"

How do u do that there is no file named environment

**Comment by didlly** [comment]
> > put token in environment and not in configuration. create a variable in environment and name it "token"
> 
> How do u do that there is no file named environment

In the env vars tab.
