### ISSUE TITLE
Blackjack - Consistently forfeiting

### ISSUE THREAD

**Issue by camelotpercivaltt** [didlly/grank#39]
Hi, thank you very much to didlly for this dank grinder bot!

I'm using the latest version, 2.2 and the blackjack feature now have been consistently forfeiting the game. I'm getting a lot of "You have ended the game" instead of hitting or standing.

**Comment by didlly** [comment]
> Hi, thank you very much to didlly for this dank grinder bot!
> 
> I'm using the latest version, 2.2 and the blackjack feature now have been consistently forfeiting the game. I'm getting a lot of "You have ended the game" instead of hitting or standing.

I'll look into this.

**Comment by didlly** [comment]
For me, blackjack is working fine. Are you sure something is wrong?

**Comment by camelotpercivaltt** [comment]
![image](https://user-images.githubusercontent.com/104262968/164910720-d6b14b6b-00c7-41c4-aa61-574970875080.png)
this is the log

**Comment by didlly** [comment]
> ![image](https://user-images.githubusercontent.com/104262968/164910720-d6b14b6b-00c7-41c4-aa61-574970875080.png)
> this is the log
> 
> [WARNING] | Failed to clear lag from the `pls blackjack` command failing: `(<class 'discord.instance.ButtonInteractError'>, ButtonInteractError("Failed to interact with button on Dank Memer's response to command `pls blackjack`. Status code: 400 (expected 200 or 204)."), <traceback object at 0x000002A9C5CB7EC0>)`. Backlash expected (it would be advisable to close Grank, wait a few minutues, and re-open Grank).
> 
> @didlly 

Does Dank Memer's message say you forfitted?

**Comment by camelotpercivaltt** [comment]
> > ![image](https://user-images.githubusercontent.com/104262968/164910720-d6b14b6b-00c7-41c4-aa61-574970875080.png)
> > this is the log
> > [WARNING] | Failed to clear lag from the `pls blackjack` command failing: `(<class 'discord.instance.ButtonInteractError'>, ButtonInteractError("Failed to interact with button on Dank Memer's response to command `pls blackjack`. Status code: 400 (expected 200 or 204)."), <traceback object at 0x000002A9C5CB7EC0>)`. Backlash expected (it would be advisable to close Grank, wait a few minutues, and re-open Grank).
> > @didlly
> 
> Does Dank Memer's message say you forfitted?

yup, it says I ended the game, 


![image](https://user-images.githubusercontent.com/104262968/164912113-a8eeb388-83c6-4191-940e-0128c2f6009f.png)

**Comment by didlly** [comment]
This should now be fixed. Please re download Grank v2.2.

**Comment by camelotpercivaltt** [comment]
> This should now be fixed. Please re download Grank v2.2.

Thanks! I really appreciate your help.
Have a nice day
