### ISSUE TITLE
Search.py was working around 1 hour ago idk what happened

### ISSUE THREAD

**Issue by UnPurgable** [didlly/grank#4]
![image](https://user-images.githubusercontent.com/81527528/151076579-cfa4dc60-fb66-4d95-9cd4-ebc87d349ca2.png)

**Comment by didlly** [comment]
Hey @UnPurgable,

Please can you double-check that the value for ```timeout``` in ```/src/config.yml``` is a whole number?

**Comment by UnPurgable** [comment]
i fixed this issue, dw about it i put 6.5 instead of 6 or 7
