### ISSUE TITLE
Black Jack Bug

### ISSUE THREAD

**Issue by Sad-Day** [didlly/grank#40]
Hey, thank you so much for making this code in the first place, I appreciate it a lot. Secondly, I saw a bug for blackjack posted yesterday, and it was resolved. I am not sure what the answer was or if it will be fixed later. Could you look into this? Thank you! I downloaded the most recent link today under the macOS version for reference. 

![](https://i.imgur.com/9qWqTuU.png)

**Comment by camelotpercivaltt** [comment]
Hi, I'm also still experiencing the bug where the bot forfeit/ending the game for the blackjack eventhough I downloaded the Version 2.2 again as instructed by @didlly . Seems like the issue hasn't been fully resolved.

I also notice that the blackjack chart table seems off, whereas I'm losing money consistently compared to using the Version 2.1

Anyhow, thanks!

**Comment by didlly** [comment]
> Hi, I'm also still experiencing the bug where the bot forfeit/ending the game for the blackjack eventhough I downloaded the Version 2.2 again as instructed by @didlly . Seems like the issue hasn't been fully resolved.
> 
> I also notice that the blackjack chart table seems off, whereas I'm losing money consistently in V2.2 compared to using the Version 2.1
> 
> Anyhow, thanks!

No code relating to how the Blackjack command's logic functioned changed in v2.2. I'll still look into it again though.

**Comment by didlly** [comment]
I think I found the buh

**Comment by didlly** [comment]
Found the bug, just polishing of the release.

**Comment by didlly** [comment]
Fixed in v2.3!
