### ISSUE TITLE
`pip install -r requirements.txt` Doesn't Work on Macos

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#42]
Hello, I'm on macOS and when I try to do
`pip install -r requirements.txt`
The command prompt says
`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

*Screenshot*
<img width="697" alt="Screen Shot 2022-04-24 at 20 33 55" src="https://user-images.githubusercontent.com/90393596/164974508-30943a8a-5034-4151-bd68-24b6cc71aa77.png">

**Comment by Yoon0117** [comment]
Also, I can't find any files called
`requirements.txt`

**Comment by Yoon0117** [comment]
I just thought of this but am I supposed to make a new file called `requirements.txt`, or is the file name different?

**Comment by didlly** [comment]
Make sure you do the command in the `/src` dir - the README tells you to do it there.

**Comment by didlly** [comment]
Oh wait I just realised what's wrong. Wait a sec please.

**Comment by didlly** [comment]
Fixed. Instead, run `python installer.py`.

**Comment by Yoon0117** [comment]
Ty for replying so quick and sorry for pinging you twice in support serv

**Comment by didlly** [comment]
> Ty for replying so quick and sorry for pinging you twice in support serv

It's fine lol.

**Comment by Yoon0117** [comment]
btw for me, i have to run `python**3** installer.py` prob because of python version

**Comment by didlly** [comment]
> btw for me, i have to run `python3 installer.py` prob because of python version

Oh okay.
