### ISSUE TITLE
`python3 main.py` Doesn't work (macOS)

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#43]
When I use the command it command prompt says
<img width="682" alt="Screen Shot 2022-04-25 at 18 11 46" src="https://user-images.githubusercontent.com/90393596/165059226-ec367d90-2950-474d-8f39-798a6fe2be0d.png">

**Comment by Yoon0117** [comment]
I'm also 13 but not as smart so I have no idea what this is lol

**Comment by didlly** [comment]
You need to run `python3 installer.py` in /src first. It says so in the README

**Comment by Yoon0117** [comment]
well I located the /src by `cd /Users/name/folder/folder/grank-main/src` then did `python3 installer.py` but it doesn't work
Am I missing something

**Comment by Yoon0117** [comment]
or is there supposed to be a file called requests

**Comment by Yoon0117** [comment]
OK, I installed `requests` and `websocket` using some cmds.
After that, this shows up
<img width="996" alt="Screen Shot 2022-04-25 at 19 14 29" src="https://user-images.githubusercontent.com/90393596/165069628-a1b0555e-94b5-4a3a-a085-6b5b62109540.png">

**Comment by didlly** [comment]
Make sure you use th latest version. In school rn so can't help that much sorry

**Comment by didlly** [comment]
Make sure you use the latest version. In school rn so can't help that much sorry

**Comment by didlly** [comment]
Try searching the error up on Google.

**Comment by Yoon0117** [comment]
Ok ty i found a way to update pip and now its fixed and good to go! :)
