### ISSUE TITLE
Configuration.json error ( mobile version )

### ISSUE THREAD

**Issue by Gudd12** [didlly/grank#44]
![Screenshot_2022-04-22-19-26-25-831_com android chrome](https://user-images.githubusercontent.com/103954053/165074591-57855ac1-34f4-4c83-8904-b8c3024cd42e.jpg)
I always keep getting error can anyone explain how to solve this . The token it says is invalid in my computer it works fine ;-;.

**Comment by Yoon0117** [comment]
I'm not the creator or a helper of any kind, but I think you wrote the wrong token on your `configuration.json`

**Comment by didlly** [comment]
The replit version is old and unsupported anymore.
