### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#45]
One think, just if you have lot of time and are bored...

One thing is that even if you get an item or money in scout and crime, the log says `Received no coins & no items from the `pls crime` command.`

Second thing is to make it so that users can choose which places they want to choose the most, for example
`1: Soul's Chamber
2: Grass
3: Air
4: Pheonix Pits
5: Crawlspace`
I mean, I DONT need it for any reasons, but you know for ppl who want to get items

If you can't do these, I'm perfectly fine because I have no idea how this works at the first place.
P.S. I LOVE GRANK

**Comment by didlly** [comment]
> One think, just if you have lot of time and are bored...
> 
> One thing is that even if you get an item or money in scout and crime, the log says `Received no coins & no items from the `pls crime` command.`
> 
> Second thing is to make it so that users can choose which places they want to choose the most, for example `1: Soul's Chamber 2: Grass 3: Air 4: Pheonix Pits 5: Crawlspace` I mean, I DONT need it for any reasons, but you know for ppl who want to get items
> 
> If you can't do these, I'm perfectly fine because I have no idea how this works at the first place. P.S. I LOVE GRANK

The `pls crime` and `pls search` item checker does work.
![image](https://user-images.githubusercontent.com/94558954/165118375-7cf0251b-ae70-42c4-863c-2a5cc46d4467.png)
![image](https://user-images.githubusercontent.com/94558954/165118411-9b7d8f6a-ca72-4f99-9956-fb1d1c2bbf58.png)

**Comment by Yoon0117** [comment]
What about the search order one?

Also, how do I add custom cmds for like `pls bet 1500` and `pls slots 1`

**Comment by didlly** [comment]
> What about the search order one?
> 
> Also, how do I add custom cmds for like `pls bet 1500` and `pls slots 1`

I'll add the custom Search order soon.

For adding custom commands, copy the code for the existing custom command and change it for  the custom command you want.

**Comment by Yoon0117** [comment]
> > What about the search order one?
> > Also, how do I add custom cmds for like `pls bet 1500` and `pls slots 1`
> 
> I'll add the custom Search order soon.
> 
> For adding custom commands, copy the code for the existing custom command and change it for the custom command you want.

Can you please add commands for bet and slots

**Comment by didlly** [comment]
> > > What about the search order one?
> > > Also, how do I add custom cmds for like `pls bet 1500` and `pls slots 1`
> > 
> > 
> > I'll add the custom Search order soon.
> > For adding custom commands, copy the code for the existing custom command and change it for the custom command you want.
> 
> Can you please add commands for bet and slots

What do you mean, you can add a custom command for the pls bet and pls slots command.

**Comment by Nostorian** [comment]
![image](https://user-images.githubusercontent.com/90422483/168220468-8a29627a-1cb2-4965-8272-2f150cceea2e.png)
sure does and now i am more richer than elon musk and as bonus i broke the economy too 
ty grank 🙏 

p.s. no hate for the tool lol

> > One think, just if you have lot of time and are bored...
> > One thing is that even if you get an item or money in scout and crime, the log says `Received no coins & no items from the `pls crime` command.`
> > Second thing is to make it so that users can choose which places they want to choose the most, for example `1: Soul's Chamber 2: Grass 3: Air 4: Pheonix Pits 5: Crawlspace` I mean, I DONT need it for any reasons, but you know for ppl who want to get items
> > If you can't do these, I'm perfectly fine because I have no idea how this works at the first place. P.S. I LOVE GRANK
> 
> The `pls crime` and `pls search` item checker does work. ![image](https://user-images.githubusercontent.com/94558954/165118375-7cf0251b-ae70-42c4-863c-2a5cc46d4467.png) ![image](https://user-images.githubusercontent.com/94558954/165118411-9b7d8f6a-ca72-4f99-9956-fb1d1c2bbf58.png)

**Comment by didlly** [comment]
> ![image](https://user-images.githubusercontent.com/90422483/168220468-8a29627a-1cb2-4965-8272-2f150cceea2e.png)
> sure does and now i am more richer than elon musk and as bonus i broke the economy too 
> ty grank 🙏 
> 
> p.s. no hate for the tool lol
> 
> > > One think, just if you have lot of time and are bored...
> > > One thing is that even if you get an item or money in scout and crime, the log says `Received no coins & no items from the `pls crime` command.`
> > > Second thing is to make it so that users can choose which places they want to choose the most, for example `1: Soul's Chamber 2: Grass 3: Air 4: Pheonix Pits 5: Crawlspace` I mean, I DONT need it for any reasons, but you know for ppl who want to get items
> > > If you can't do these, I'm perfectly fine because I have no idea how this works at the first place. P.S. I LOVE GRANK
> > 
> > The `pls crime` and `pls search` item checker does work. ![image](https://user-images.githubusercontent.com/94558954/165118375-7cf0251b-ae70-42c4-863c-2a5cc46d4467.png) ![image](https://user-images.githubusercontent.com/94558954/165118411-9b7d8f6a-ca72-4f99-9956-fb1d1c2bbf58.png)
> 
> 

Sometimes it works, but when the latest message in the channel is different (let's say a level up message with emojis, which contains codes with numbers), it can make it confused lol.

**Comment by didlly** [comment]
Moved to #66
