### ISSUE TITLE
Uhm am kinda scared now

### ISSUE THREAD

**Issue by sneazy-ibo** [didlly/grank#48]
https://www.virustotal.com/gui/file/1708f494aeab6a4257d960530552029ccdf32f13bfbc8a1826f950992678ea22?nocache=1

**Comment by didlly** [comment]
Uh, run from source I guess?

**Comment by Nostorian** [comment]
if you feel unsafe running the exe from the [release](https://github.com/didlly/grank/releases/tag/v2.3), then you can just download [golang](https://go.dev/doc/install) and [download the source](https://github.com/didlly/grank/archive/refs/heads/main.zip)

pretty sure you can work it out
