### ISSUE TITLE
Program unable to run on mac "No module named 'utils.Yaml'"

### ISSUE THREAD

**Issue by Sad-Day** [didlly/grank#50]
Hey again, 
The rewrite looks extremely promising and good luck with the re-write after dank memer switches to slash commands. 

Issue: ": No module named 'utils.Yaml'"
<img width="370" alt="z" src="https://user-images.githubusercontent.com/96270789/166622206-2073a3d1-023e-4eba-ad1e-e44e4956c9f6.png">

On Mac, the newest version of grank.

**Comment by didlly** [comment]
Uh yeah, this was fixed. Please redownload the latest version of Grank. Like I said in the Discord server, this was because git ignores file capitalization changes, and I had changed the capitalisation of some files.
