### ISSUE TITLE
`config.yaml`

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#51]
Where can I find the `config.yaml` in the newest version?

Cause I'm trying to disable all cmds except for bj and snakeeyes for XP, and it's quite annoying to turn everything off one by one, also if I try to change many settings at once for other purposes.

If there is no `config.yaml`, then plz tell me where the config data is stored

**Comment by didlly** [comment]
> Where can I find the `config.yaml` in the newest version?
> 
> Cause I'm trying to disable all cmds except for bj and snakeeyes for XP, and it's quite annoying to turn everything off one by one, also if I try to change many settings at once for other purposes.
> 
> If there is no `config.yaml`, then plz tell me where the config data is stored

The yml file is located in `/src/database/{account_id}/config/.yml`.

**Comment by Yoon0117** [comment]
ok, ty
