### ISSUE TITLE
Grank start command

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#52]
can you make it so that grank automatically deletes the starting cmd and `succesfully started text` so that others cant see it

**Comment by didlly** [comment]
You can easily delete it yourself. But I'll think about this feature.

**Comment by Yoon0117** [comment]
OK so my friend was trying this out and 
YES, he deleted the `grank start, grinder started` msgs. But even after this, a mod saw the msg edit log, and after mod came, he got Banned from his favorite serv. Can you make it so that You can have another option which is to use Terminal to start grank?? I Really Need This If I'm Going To Use The Program

**Comment by didlly** [comment]
> > @Yoon0017 I'll add an autostart feature soon. In the meantime, just use an older version.
> 
> Ok, Thank you.

I've added an autostart feature. Currently I'm too tried to add a helper command for this, so just add the channel id of the channel to automatically start the grinder in the list of channels in the subconfig `auto start` (make sure the key `enabled` is set to `True`). I'll add a helper command later.

**Comment by Yoon0117** [comment]
Ok, Thank You. 

P.S. He got blacklisted from dank for 9999 days (27 years).

**Comment by didlly** [comment]
> Ok, Thank You.
> 
> P.S. He got blacklisted from dank for 9999 days (27 years).

Dang.
