### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#53]
<img width="462" alt="Screen Shot 2022-05-05 at 15 49 25" src="https://user-images.githubusercontent.com/90393596/166875052-27c0d117-5060-4f43-be29-49d5b7d4e548.png">
You can Probably know what this means

**Comment by didlly** [comment]
> <img alt="Screen Shot 2022-05-05 at 15 49 25" width="462" src="https://user-images.githubusercontent.com/90393596/166875052-27c0d117-5060-4f43-be29-49d5b7d4e548.png">
> You can Probably know what this means

You didn't listen to the instructions lol.

**Comment by Sxvxgee** [comment]
Actually that's a bug. As you can see in the note, where it says  "to enable the custom command, run..." and shows an example, but there isn't underscores while there is in the other examples.

**Comment by didlly** [comment]
> Actually that's a bug. As you can see in the note, where it says  "to enable the custom command, run..." and shows an example, there isn't underscores while there is in the other examples. Confusing some people into thinking you don't need underscores in order to enable a command but only need underscores when doing other things.

Ah I see, thanks for this lol.

**Comment by didlly** [comment]
Fixed!
