### ISSUE TITLE
Auto Adventure

### ISSUE THREAD

**Issue by purpl3r0se** [didlly/grank#54]
I have an idea for creating an automatic adventure ticket thingy, it shouldn't be that hard since you already have trivia and for adventure its kinda like pls stream but more random questions/answers and gotta test atleast most of them to know what they do and what's the best to do, I may try to make a PR whenever I'm home as currently I'm in school.

**Comment by didlly** [comment]
The cmd will be added, but like I said in #49, it may be a while until this is added since v3 has not been released yet.

**Comment by didlly** [comment]
> > The cmd will be added, but like I said in #49, it may be a while until this is added since v3 has not been released yet.
> 
> Yeah I knew that already, just wanted to make sure it exists in v3.

I have added partial support for `pls adv`. I will add support for more outcomes when I get time. `pls adv` will be included in `v3.3-beta` or `v3.3` (whichever comes next).
