### ISSUE TITLE
Dosenot catch dragon in pls hunt

### ISSUE THREAD

**Issue by ritheshnayak** [didlly/grank#55]
**Is your feature request related to a problem? Please describe.**
please make the bot able to catch the dragon in pls hunt [...]

**Describe the solution you'd like**
make it able to press a random button if the dragon hunting comes

**Describe alternatives you've considered**
NONE, this is the best autodank grinders out there

**Additional context**
nope

**Comment by didlly** [comment]
Fixed in [this](https://github.com/didlly/grank/commit/3c4a41640c3aa3118414bf7256a36b8eb08c2b86) commit.
