### ISSUE TITLE
Randomize shifts

### ISSUE THREAD

**Issue by sneazy-ibo** [didlly/grank#56]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 

I am scared if getting my accs disabled, so I always gotta make sure to make the perfect shifts.

**Describe the solution you'd like**

A system with base and variation time like dankgrinder would be perfect.

**Describe alternatives you've considered**

**Additional context**

**Comment by didlly** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when 
> 
> I am scared if getting my accs disabled, so I always gotta make sure to make the perfect shifts.
> 
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> A system with base and variation time like dankgrinder would be perfect.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

Already exists.
