### ISSUE TITLE
is it safe?

### ISSUE THREAD

**Issue by sneazy-ibo** [didlly/grank#57]
I got 17 hits on virustotal
https://www.virustotal.com/gui/file/e4143c07648e407eabd66b3ba9ca4eb0fe79669aac47073641d19127f8b7cf4d?nocache=1

**Comment by didlly** [comment]
There are many reasons why compiled Python exes are flagged as viruses. If you do not believe me, check the whole 2000 lines of code for viruses. Then, if you think that I added a virus into the exe, reverse engineer it and check that code. Then, if you still think the compiled exe is unsafe, don't use Grank ;-).

https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg

**Comment by sneazy-ibo** [comment]
Yuh I believe you, I am using grank for a while now. I just wondered why chrome flagged it as a malware bc the last version that I used didn't flagged it. But thx for the confirmation
