### ISSUE TITLE
Multiple feature requests

### ISSUE THREAD

**Issue by sneazy-ibo** [didlly/grank#58]
> I couldn't decide if I should use your selfbot or dankgrinder, but since I've really liked the selfbot commands and their reply through a webhook. I chosed to use yours again for a while. I've thought abt your project and came up with the following requests:

###  ☑️ Clusters _(didn't know about controllers it alr does the same thing)_ 
You prolly alr know what I mean bc of dankgrinder, but it would be cool if you can add more features on the autotrader option or a new sub/category. I came up with the following Idea:
- My Idea is that we can add IDs just like controllers which will be our master/s (for the people who have never dankgrinder: master { specific acc you chose} will get items and coins sent from instances {accs that just grind} this gives you a better overview and is also safer + holds items on multiple accs). Those masters will get a through a command like `grank cluster.<masterid or cluster>.assign.<instanceid1>.<instanceid2>` other instances assigned which alr has their tokens inside the credentials. 
_(masterid for making a new cluster)_ _(clusterid or clusternumber for adding new instances to an existing cluster)_

Since the clusters feature would be a game changer I would like to list here some of the commands that are in my mind rn.
1. `grank.cluster.<start/stop>.all` or just <grank start/stop> to start/stop grinding with all clusters and tokens
1.1 `grank.cluster.<clusterid>.<start/stop>` starts or stops the mentioned cluster
3. `grank.cluster.<clusterid>.info` same as grank info but only with data abt the mentioned cluster
4. `grank.cluster.<clusterid>.remove.<instanceid1>.<instanceid2>` removes a/or more existing instance/s from a existing cluster (`....remove.all` deletes the whole cluster)
5. `grank.cluster.<clusterid>.shifts` add custom shifts for each cluster (tokens that are not in a cluster will have the default/your shifts)
6. `grank.cluster -help` shows all cluster commands + helper

### ☑️ Suffixes
It would be cool if you add a smart system which recognizes your selfbot commands shortened f.e.
- `grank conf.stg.prf = >` = `grank config.settings.prefix = >`
- `grank cmds.add.pls_kys.69` = `grank commands.add.pls_kys.69`

Recognizing the command by the first three letters or the first and last letter of each option or the first letter of each syllable or anything like that would make changes on the config through discord faster and easier since it would also solve the issue with dots and underlines with selfbot commands.

### ☐ Quick trade
I didn't saw how the auto trade feature works yet but it would be nice if it logs your items from the `pls inv` command with compact mode enabled instead checking it individually with `pls shop <itemname>`. Anyways my Idea is to add a new category like `grank start` where it doesn't grind and only trades the inv with listed items. Intigrating that with clusters would pretty nice, here my command ideas:
1. `grank.quicktrade.start` starts trading all the items from an itemlist, till it's done or cancelled with ↓
2. `grank.quicktrade.forcestop` forcefully stops the trade process
3. `grank.clusters.<clusterid>.quicktrade.start` starts the quick trading process of the mentioned cluster
4. `grank.clusters.<clusterid>.quicktrade.forcestop` forcefully stops the quick trading process of the mentioned cluster
5. `grank.quicktrade -help` shows all quicktrade commands + helper

### ☑️ Webhook bypass ratelimits
The webhook always gets ratelimited if I run `grank config`. I think the webhook sents the messages too quickly or that it just can't send so many embeds in a short amount of time, here are my Ideas on how to solve this:
- First one is to make a custom category under configs for custom webhook delays between messages:
1. `grank.config.webhook_delay.enable = True/False` option to enable webhook delays
2. `grank.config,webhook_delays.minimum = 0` minimum delay for sending embeds through a webhook
3. `grank.config,webhook_delays.maximum = 0` maximum delay for sending embeds through a webhook
- Second one is to add multiple webhooks which are sending the embeds alternately before a rate limit. So that one can "rest" whilst the other is sending a embed. Combining this with the mentioned webhook delay would be perfect.

### ☑️ More webhook logs features
The webhook logging subcategory is pretty new and I would like to suggest the abbility for custom replies for events (additing warnings to webhook logs would be really nice btw) where you can add a ID in the reply to ping a user for example or just to customize the text for each event. Another thing that I would be pretty unique is to add a clickable message link for each event (only available for bots/webhooks `[text](messagelink)`) to know from where it comes.

### ☐ Auto update
It would be pretty nice if you can add a new python file which fetches _your_ new commits from github and merges them directly inside our grank folder. This would finally stop the process of downloading the sc to displace the updated files. It would be good if you also add some ignores like the credentials file (for the case it gets accidentally updated) or lines like the `"username":` and the `"avatar_url": ` in /src/discord/Gateway.py what I would really appreciate. The absolut best way would be that it merges only the fetched lines from new commits instead of the whole files.

### ☑️ Shift state
Press add at the `grank info` a new embed with three new fields that show you which shift is currently running and time information. The time since when the shift started and how much time is left would be displayable through epoch timestamps. 

### ☐ Auto trending game
That is smth that would requiere a bit of more coding, so my Idea is that _you_ have like 4-6 tokens cycling everyday only through `pls stream` to check which game is trending everyday. This would be also very helpful bc the current stream feature stops all the other commands if the stream alr ended and sent `pls stream` bc of the option where we have to chose the game to stream, grank just keeps sending commands but none of them will get a response from dankmemer till grank waited 5min, you selected a game or the `End Interaction`. is clicked. Those accounts that you or anyone host to find the trending game will inform all clients everyday, so that it's already set before the main.py starts. Optional would be a global msg that sends a message through grank users `webhook logging` feature, when one of those 4-6 tokens got a hit on the trending game so that we know when to start the main.py to use the right trending game (I don't know if it's possible for grank to fetch data whilst grinding but amma assume not). This would be a win-win-win situation bc it would fix the bug with the `pls stream` feature, enhance it too and also add a new value for the webhook logger.

### ☐ Spoof alerts
One of the feature that I like the most on selfbots are spoof alerts, spoof alerts check specific channels (in our case the grind channel) till anyone sent a message in that channel that you have marked as a spoof. This results into a sent message from your webhook that pings and messages you with the message link of the message that contains the word that you have whitelisted. I can imagine this as a subcategory like `logging` just like `webhook log`. I am thinking of the following commands for that category:
1. `grank.config.logging.spoof_alerts = True/False` enabling or disable spoof alerts
2. `grank.config.logging.spoof_alerts.add.<anytext>` adding new keywords to your spoof whitelist
3. `grank.config.logging.spoof_alerts.remove.<anytext>` removing mentioned keywords from your spoof whitelist
4. `grank.config.logging.spoof_alerts.keywords` shows your spoof whitelist
5. `grank.config.logging.spoof_alerts.webhook.<link>` replaces your webhook if you want a custom one otherwise uses default
6. `grank.config.logging.spoof_alerts -help` shows all spoof alert commands + helper

**Comment by didlly** [comment]
> > I couldn't decide if I should use your selfbot or dankgrinder, but since I've really liked the selfbot commands and their reply through a webhook. I chosed to use yours again for a while. I've thought abt your project and came up with the following requests:
> 
> ### Clusters
> 
> You prolly alr know what I mean bc of dankgrinder, but it would be cool if you can add more features on the autotrader option or a new sub/category. I came up with the following Idea:
> 
>     * My Idea is that we can add IDs just like controllers which will be our master/s (for the people who have never dankgrinder: master { specific acc you chose} will get items and coins sent from instances {accs that just grind} this gives you a better overview and is also safer + holds items on multiple accs). Those masters will get a through a command like `grank cluster.<masterid or cluster>.assign.656486515341.54454645121.465465465546` other instances assigned which alr has their tokens inside the credentials.
>       _(masterid for making a new cluster)_ _(clusterid or clusternumber for adding new instances to an existing cluster)_
> 
> 
> Since the clusters feature would be a game changer I would like to list here some of the commands that are in my mind rn.
> 
>     1. `grank.cluster.<start/stop>.all` or just <grank start/stop> to start/stop grinding with all clusters and tokens
>        1.1 `grank.cluster.<clusterid>.<start/stop>` starts or stops the mentioned cluster
> 
>     2. `grank.cluster.<clusterid>.info` same as grank info but only with only data abt the mentioned cluster
> 
>     3. `grank.cluster.<clusterid>.remove.<instanceid>` removes a existing instances from a existing cluster (`....remove.all` deletes the whole cluster)
> 
>     4. `grank.cluster.<clusterid>.shifts` add custom shifts for each cluster (tokens that are not in a cluster will have the default/your shifts)
> 
> 
> ### Suffixes
> 
> It would be cool if you add a smart system which recognizes your selfbot commands shortened f.e.
> 
>     * `grank conf.stg.prf = >` = `grank config.settings.prefix = >`
> 
>     * `grank cmds.add.pls_kys.69` = `grank commands.add.pls_kys.69`
> 
> 
> Recognizing the command by the first three letters or the first and last letter of each option or the frirst letter of each syllable or anything like that. This would make changes on the config through discord faster and easier since it would also solve the issue with dots and underlines.
> ### Quick trade
> 
> I didn't saw how the auto trade feature works yet but it would be nice if it logs your items from the `pls inv` command instead checking it individually with `pls shop <itemname>`. Anyways my Idea is to add a new category like `grank start` where it doesn't grind and only trades the inv with listed items. Intigrating that with clusters would pretty nice, here my command ideas:
> 
>     1. `grank.quicktrade.start` starts trading all the items from the a itemlist, till it's done or cancelled with ↓
> 
>     2. `grank.quicktrade.forcestop` forcefully stops the trade process
> 
>     3. `grank.clusters.<clusterid>.quicktrade.start` starts the quick trading process of the mentioned mentioned cluster
> 
>     4. `grank.clusters.<clusterid>.quicktrade.forcestop` forcefully stops the quick trading process of the mentioned cluster
> 
> 
> ### Webhook bypass ratelimits
> 
> The webhook always gets ratelimited if I run `grank config`. I think the webhook sents the messages too quickly or that it just can't send so many embeds in a short amount of time, here are my Ideas on how to solve this:
> 
>     * First one is to make a custom category under configs for custom webhook delays between messages:
> 
> 
>     1. `grank.config.webhook_delay.enable.<True/False>` option to enable webhook delays
> 
>     2. `grank.config,webhook_delays.minimum = 0` minimum delay for sending embeds through a webhook
> 
>     3. `grank.config,webhook_delays.maximum = 0` maximum delay for sending embeds through a webhook
> 
> 
>     * Second one is to addmultiple webhooks which sent them embeds alternately before a rate limit. So that one can "rest" whilst the other is sending a embed. Combining this with the mentioned webhook delay would be perfect.
> 
> 
> ### Custom reply
> 
> The webhook logging subcategory is pretty new and I would like to suggest the abbility for custom replies for events (additing warnings to webhook logs would be really nice) where you can add a ID in the reply to ping a user for example or just customize the text for each event.

I'll start having a look at adding these features tomorrow since I'm tired today after my exam.

**Comment by didlly** [comment]
Added proper webhook ratelimit handling (now sleeps for the time Discord specifies, which is in milliseconds, not seconds for some reason lol).

**Comment by didlly** [comment]
> > I couldn't decide if I should use your selfbot or dankgrinder, but since I've really liked the selfbot commands and their reply through a webhook. I chosed to use yours again for a while. I've thought abt your project and came up with the following requests:
> 
> ### Clusters
> 
> You prolly alr know what I mean bc of dankgrinder, but it would be cool if you can add more features on the autotrader option or a new sub/category. I came up with the following Idea:
> 
>     * My Idea is that we can add IDs just like controllers which will be our master/s (for the people who have never dankgrinder: master { specific acc you chose} will get items and coins sent from instances {accs that just grind} this gives you a better overview and is also safer + holds items on multiple accs). Those masters will get a through a command like `grank cluster.<masterid or cluster>.assign.<instanceid1>.<instanceid2>` other instances assigned which alr has their tokens inside the credentials.
>       _(masterid for making a new cluster)_ _(clusterid or clusternumber for adding new instances to an existing cluster)_
> 
> 
> Since the clusters feature would be a game changer I would like to list here some of the commands that are in my mind rn.
> 
>     1. `grank.cluster.<start/stop>.all` or just <grank start/stop> to start/stop grinding with all clusters and tokens
>        1.1 `grank.cluster.<clusterid>.<start/stop>` starts or stops the mentioned cluster
> 
>     2. `grank.cluster.<clusterid>.info` same as grank info but only with data abt the mentioned cluster
> 
>     3. `grank.cluster.<clusterid>.remove.<instanceid1>.<instanceid2>` removes a/or more existing instance/s from a existing cluster (`....remove.all` deletes the whole cluster)
> 
>     4. `grank.cluster.<clusterid>.shifts` add custom shifts for each cluster (tokens that are not in a cluster will have the default/your shifts)
> 
> 
> ### Suffixes
> 
> It would be cool if you add a smart system which recognizes your selfbot commands shortened f.e.
> 
>     * `grank conf.stg.prf = >` = `grank config.settings.prefix = >`
> 
>     * `grank cmds.add.pls_kys.69` = `grank commands.add.pls_kys.69`
> 
> 
> Recognizing the command by the first three letters or the first and last letter of each option or the first letter of each syllable or anything like that would make changes on the config through discord faster and easier since it would also solve the issue with dots and underlines with selfbot commands.
> ### Quick trade
> 
> I didn't saw how the auto trade feature works yet but it would be nice if it logs your items from the `pls inv` command instead checking it individually with `pls shop <itemname>`. Anyways my Idea is to add a new category like `grank start` where it doesn't grind and only trades the inv with listed items. Intigrating that with clusters would pretty nice, here my command ideas:
> 
>     1. `grank.quicktrade.start` starts trading all the items from an itemlist, till it's done or cancelled with ↓
> 
>     2. `grank.quicktrade.forcestop` forcefully stops the trade process
> 
>     3. `grank.clusters.<clusterid>.quicktrade.start` starts the quick trading process of the mentioned cluster
> 
>     4. `grank.clusters.<clusterid>.quicktrade.forcestop` forcefully stops the quick trading process of the mentioned cluster
> 
> 
> ### Webhook bypass ratelimits
> 
> The webhook always gets ratelimited if I run `grank config`. I think the webhook sents the messages too quickly or that it just can't send so many embeds in a short amount of time, here are my Ideas on how to solve this:
> 
>     * First one is to make a custom category under configs for custom webhook delays between messages:
> 
> 
>     1. `grank.config.webhook_delay.enable.<True/False>` option to enable webhook delays
> 
>     2. `grank.config,webhook_delays.minimum = 0` minimum delay for sending embeds through a webhook
> 
>     3. `grank.config,webhook_delays.maximum = 0` maximum delay for sending embeds through a webhook
> 
> 
>     * Second one is to add multiple webhooks which are sending the embeds alternately before a rate limit. So that one can "rest" whilst the other is sending a embed. Combining this with the mentioned webhook delay would be perfect.
> 
> 
> ### Custom webhook logs
> 
> The webhook logging subcategory is pretty new and I would like to suggest the abbility for custom replies for events (additing warnings to webhook logs would be really nice btw) where you can add a ID in the reply to ping a user for example or just to customize the text for each event.

I have added suffixes.

**Comment by sneazy-ibo** [comment]
> I have added suffixes.

Are they written manually or smart?

**Comment by didlly** [comment]
Written manually.

**Comment by sneazy-ibo** [comment]
> Written manually.

Ah I see, sry I didn't checked the sc yet. Also how do I add more [suffixes](https://github.com/didlly/grank/blob/main/src/discord/Gateway.py#L1464), is it smth easy I can do or does it require any coding.

**Comment by didlly** [comment]
> > Written manually.
> 
> Ah I see, sry I didn't checked the sc yet. Also how do I add more [suffixes](https://github.com/didlly/grank/blob/main/src/discord/Gateway.py#L1464), is it smth easy I can do or does it require any coding.
> 
> Do I need to add `or args.command ==` for other suffixes on the same line or is there a other way to do that?

You would have to add `or args.command ==` for other suffixes.

**Comment by didlly** [comment]
Lines like `username:` / `avatar_url:` are on purpose filled in in `/src/discord/Gateway.py`.

**Comment by didlly** [comment]
I have added shifts stats to the `info` command.

**Comment by sneazy-ibo** [comment]
> Lines like `username:` / `avatar_url:` are on purpose filled in in `/src/discord/Gateway.py`.

Ye but I mean like for the case that the Gateway.py gets updated. I always need to replace those lines.

**Comment by didlly** [comment]
> > Lines like `username:` / `avatar_url:` are on purpose filled in in `/src/discord/Gateway.py`.
> 
> Ye but I mean like for the case that the Gateway.py gets updated. I always need to replace those lines.

Those lines are meant to be there lol.

**Comment by sneazy-ibo** [comment]
> > Ye but I mean like for the case that the Gateway.py gets updated. I always need to replace those lines.
> 
> Those lines are meant to be there lol.

I see I see. What about spoof alerts will grank have that feature in future?

**Comment by didlly** [comment]
Coming soon lol.
