### ISSUE TITLE
Problem opening Grank

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#59]
![image](https://user-images.githubusercontent.com/90393596/169641993-e55a629e-312c-4878-b9b1-b35a9dbcd497.png)

Yes, I was in Mac before, but now I'm tired of the Lag and moved to my gaming PC
So its first time using Grank on this device, and after using cmd `grank autostart add 0` (I put channel id instead of `0`), then app crashed. Now I can't open grank, with the msg in the photo above. Idk what this is, help me plz

**Comment by didlly** [comment]
> ![image](https://user-images.githubusercontent.com/90393596/169641993-e55a629e-312c-4878-b9b1-b35a9dbcd497.png)
> 
> Yes, I was in Mac before, but now I'm tired of the Lag and moved to my gaming PC So its first time using Grank on this device, and after using cmd `grank autostart add 0` (I put channel id instead of `0`), then app crashed. Now I can't open grank, with the msg in the photo above. Idk what this is, help me plz

Please update to the latest version.

**Comment by didlly** [comment]
This bug has been fixed in the code but a fixed release has not been relaeased yet.

**Comment by Yoon0117** [comment]
> This bug has been fixed in the code but a fixed release has not been released yet.

so what am I supposed to do?

**Comment by didlly** [comment]
> > This bug has been fixed in the code but a fixed release has not been released yet.
> 
> so what am I supposed to do?

Get the latest version of the source code.

**Comment by Yoon0117** [comment]
ok

**Comment by Yoon0117** [comment]
wait so does that mean I have to run from source code, which means I have to run the `python3` code on WIndows?

**Comment by Yoon0117** [comment]
![image](https://user-images.githubusercontent.com/90393596/169646120-b4382010-9da7-4734-b911-f45abd5fd225.png)
I can't get it to work in the latest update rip

**Comment by Yoon0117** [comment]
OH Im so dumb
I put the channel id to `0` so that's why it didn't work on latest version...
Well it works find now.
