### ISSUE TITLE
doesnt detect who dank is responding to

### ISSUE THREAD

**Issue by Erix-glitch** [didlly/grank#6]
**Describe the bug**
A clear and concise description of what the bug is
When someone else uses dank memer, the program parses their embed instead of ours. This results in a crash

**To Reproduce**
1. Wait for someone to use dank memer
2. The program will error
**Expected behavior**
The program checks who dank memer is responding to 

**Screenshots**
![image](https://user-images.githubusercontent.com/71719838/151681701-ccd3a0ea-f8c3-4d9e-98bc-ba0be167b1d6.png)

**Additional context**

**Comment by didlly** [comment]
Hi @Erix-glitch,

This is why in the ```README.md```, it is says that it is best for you to run the program in a channel which only you and Dank Memer can send messages in. That being said, I will commit an update to fix this bug later.

**Comment by didlly** [comment]
Should be fixed in [this](https://github.com/didlly/grank/commit/eb6d360ca8e788b3ed68374d65a3fb9cb4571040) commit. I added a function which will check who Dank Memer is responding to.
