### ISSUE TITLE
pls blackjack Bug

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#60]
![image](https://user-images.githubusercontent.com/90393596/169646702-1fd4cb08-ad6f-4d75-9b2d-fce8d1de608e.png)
So I'm using the `pls blackjack max` command, and grank often doesn't interact until Dank Memer says `You Didn't Respond in Time`, which makes me lose the game and lose 250k each time.

The weird thing is that Grank starts working again right after I manually interact with the buttons. Then after it sends 2 or 3 more commands, it goes offline again, then goes online on the next BJ.
Please Fix this, My profits are getting lower the longer I go AFK.

**Comment by didlly** [comment]
Please do not make issue requests about problems that only you are facing - everyone else has no `pls bj` related bugs.

**Comment by Yoon0117** [comment]
> Please do not make issue requests about problems that only you are facing - everyone else has no `pls bj` related bugs.

Does that mean that This bug cannot be fixed? If you can't, can I just know what's causing this error? (Cause this is happening Every Time)
