### ISSUE TITLE
Where to find `autostart chan id`

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#61]
Hi, using one file ver. for Windows
Where can I find file with the `autostart channel id`? Whenever I open the program it instantly says this
![image](https://user-images.githubusercontent.com/90393596/169822830-51c4c69e-cb5e-4106-a676-c274f9673807.png)
(I accidently did `grank autostart add 0` or some cmd Idk what it is.)
Help me

**Comment by sneazy-ibo** [comment]
> Hi, using one file ver. for Windows
> Where can I find file with the `autostart channel id`? Whenever I open the program it instantly says this
> ![image](https://user-images.githubusercontent.com/90393596/169822830-51c4c69e-cb5e-4106-a676-c274f9673807.png)
> (I accidently did `grank autostart add 0` or some cmd Idk what it is.)
> Help me

Reset the database
