### ISSUE TITLE
Improvement for `pls adv`

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#62]
Hi,
I just saw that Grank is pressing `Collect` option in Odd Eye, `Flee` in alien abduction, etc, which are not what I want to press, and probably for many people. Is it possible for you to make another file called `adv_info` or smth for us to choose what Grank presses?
(Also the cooldown in config file is 5 minutes, but adv cooldown is actually 2 mins.)

Another suggestion is

**Comment by didlly** [comment]
Collect is better.

**Comment by Yoon0117** [comment]
Well, nobody has ever gotten the odd eye front collect and if you think you can get it, sure.
But some ppl might think it's not, so I was just suggesting

**Comment by Yoon0117** [comment]
Like it could be a good improvement

**Comment by Yoon0117** [comment]
Ok, but I'm just sayin it would be a very nice/convenient feature

**Comment by Yoon0117** [comment]
@didlly Or is there a way for me to manually change the interact options myself? If yes, which file is it/how do I change the option

**Comment by didlly** [comment]
Grank automtaically chooses the best option - there is no way to change it apart from changing the code found in `/src/scripts/adventure.py`.

**Comment by Yoon0117** [comment]
> Grank automtaically chooses the best option - there is no way to change it apart from changing the code found in `/src/scripts/adventure.py`.

Thank you for this, can I just ask which line I have to change to change the options?

**Comment by Yoon0117** [comment]
@didlly
