### ISSUE TITLE
New change

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#65]
![image](https://user-images.githubusercontent.com/90393596/170822049-19c5a811-803f-4974-943d-95e6d4f401d6.png)
![image](https://user-images.githubusercontent.com/90393596/170822078-3a0cb530-0eee-48e7-bad2-81baefb15177.png)

**Comment by Yoon0117** [comment]
If I just change that line back to before, 
![image](https://user-images.githubusercontent.com/90393596/170822208-b44fd9cc-f828-482f-a7b5-0506ab1435e5.png)
This happens but continues sending cmds

**Comment by didlly** [comment]
> ![image](https://user-images.githubusercontent.com/90393596/170822049-19c5a811-803f-4974-943d-95e6d4f401d6.png) ![image](https://user-images.githubusercontent.com/90393596/170822078-3a0cb530-0eee-48e7-bad2-81baefb15177.png)

You forgot to update `/src/database/Verifier.py`.

**Comment by Yoon0117** [comment]
ok ill retry one sec

**Comment by didlly** [comment]
That was the cause of both errors.

**Comment by Yoon0117** [comment]
yes, ty

**Comment by didlly** [comment]
> yeh, ty

Np.
