### ISSUE TITLE
Avoiding Death

### ISSUE THREAD

**Issue by kaanalp28** [didlly/grank#66]
**Restriction of some commands to avoid death, especially in pls search and pls crime.** 

The bot doesn't care if you die. I just died and lost all my money. I had 30+ life savers in my inventory but they got used one by one in 7 hours. 

 

https://www.reddit.com/r/dankmemer/comments/igi0gy/pls_search_option_statistics/  Here is a link of pls search death rate chart. I would recommend a setting such as 
`Death rate limit: Enabled
Limit: Enter the percentage of death you want as max.`

```
Enable death rate limit: True
Limit: 7.5
```

(for example, I would not want to risk having more than 7.5% death probability

You can also add an option so if its more than 0% (no risk of death), it wont work (only uses the commands that has no death risk.)  

**I have considered disabling pls search and pls crime altogether, but that makes it vey unefficient and the main reason im using grank is because it can click to buttons.** 

  

**An auto lifesaver buyer might also be useful (buys a lifesaver if there isnt any left, or buys one everytime the user dies to keeo the lifesaver amount stable** 

`Auto life: True`

I would also recommend adding an auto shut down so if enabled it shuts down after set amount of time (like 5 hours, 10 hours etc.) 

```
Auto shutdown: True
Hours: True/False
Amount: 6(Hours)/21600(Seconds)
```

**Comment by sneazy-ibo** [comment]
Solution: 

```yml
custom commands: 
   enabled: False 
    
   pls buy sav 1: 
     enabled: True 
     cooldown: 189
```

Autoshutdown is a nice Idea but you can manage this with shifts already

**Comment by didlly** [comment]
> Solution:
> 
> ```yaml
> custom commands: 
>    enabled: True
>     
>    pls buy sav 1: 
>      enabled: True 
>      cooldown: 189
> ```
> 
> Autoshutdown is a nice Idea but you can manage this with shifts already

Casually pasets code for custom commands by accident.

**Comment by sneazy-ibo** [comment]
> Casually pastes code for custom commands by accident.

Lmao I did that for the case that he doesn't know what I where that code belongs

**Comment by kaanalp28** [comment]
Thanks for the idea about shifts, I'm looking forward to see how the pls crime and search customization turns out.

**Comment by Yoon0117** [comment]
> The next item on my todo was to add the ability to customize search and crime places, so that fits in nicely. As well as this, I do not see much point in auto shutdown. As a workaround, add a shift with an active session of how long you want the bot to run for, and a passive session of a very large number (e.g, `18446744073709551615`).

THank you for actually bringing this idea as a feature!

**Comment by didlly** [comment]
Added, please follow instructions at the following addresses:

https://didlly.github.io/grank/users/#crime-category
https://didlly.github.io/grank/users/#search-category

 Auto lifesaver on death (slightly different to auto lifesaver) will be added soon.
