### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#67]
in the config file, there are two of search and crime command enabling, one at the top along with other commands and on at the buttom with the random option, and idk which one I have to enable

<img width="143" alt="Screen Shot 2022-06-04 at 8 06 35" src="https://user-images.githubusercontent.com/90393596/171965369-82265afb-213a-4dd0-96db-e182fbeccd7c.png">
<img width="146" alt="Screen Shot 2022-06-04 at 8 06 45" src="https://user-images.githubusercontent.com/90393596/171965378-66984c65-11e0-40bc-95b6-1995637b4ec8.png">

**Comment by didlly** [comment]
> in the config file, there are two of search and crime command enabling, one at the top along with other commands and on at the buttom with the random option, and idk which one I have to enable
> 
> <img alt="Screen Shot 2022-06-04 at 8 06 35" width="143" src="https://user-images.githubusercontent.com/90393596/171965369-82265afb-213a-4dd0-96db-e182fbeccd7c.png">
> 
> <img alt="Screen Shot 2022-06-04 at 8 06 45" width="146" src="https://user-images.githubusercontent.com/90393596/171965378-66984c65-11e0-40bc-95b6-1995637b4ec8.png">

Reset your database. It happened because Grank detected the database was missing some keys that were added in the latest update, and added them, but it preserved the old options as well. Use the link I gave you before in the other issue to understand how random works.

**Comment by Yoon0117** [comment]
Ok ty for this
also i have another thing

Idk if this is meant to be like this or not but
<img width="110" alt="Screen Shot 2022-06-04 at 18 38 27" src="https://user-images.githubusercontent.com/90393596/171995201-fc861882-1bd0-45b2-86b7-7a572218d2f0.png">
<img width="92" alt="Screen Shot 2022-06-04 at 18 38 31" src="https://user-images.githubusercontent.com/90393596/171995202-965b98e9-827e-4a48-8024-022d7e01f56b.png">
<img width="92" alt="Screen Shot 2022-06-04 at 18 38 41" src="https://user-images.githubusercontent.com/90393596/171995204-96761d9f-8761-4eb4-878e-d94d4aaf5450.png">
all these lines are connected to each other
so should I disconnect them with a blank line

**Comment by didlly** [comment]
> Ok ty for this also i have another thing
> 
> Idk if this is meant to be like this or not but <img alt="Screen Shot 2022-06-04 at 18 38 27" width="110" src="https://user-images.githubusercontent.com/90393596/171995201-fc861882-1bd0-45b2-86b7-7a572218d2f0.png"> <img alt="Screen Shot 2022-06-04 at 18 38 31" width="92" src="https://user-images.githubusercontent.com/90393596/171995202-965b98e9-827e-4a48-8024-022d7e01f56b.png"> <img alt="Screen Shot 2022-06-04 at 18 38 41" width="92" src="https://user-images.githubusercontent.com/90393596/171995204-96761d9f-8761-4eb4-878e-d94d4aaf5450.png"> all these lines are connected to each other so should I disconnect them with a blank line

Doesn't matter

**Comment by Yoon0117** [comment]
> > Ok ty for this also i have another thing
> > Idk if this is meant to be like this or not but <img alt="Screen Shot 2022-06-04 at 18 38 27" width="110" src="https://user-images.githubusercontent.com/90393596/171995201-fc861882-1bd0-45b2-86b7-7a572218d2f0.png"> <img alt="Screen Shot 2022-06-04 at 18 38 31" width="92" src="https://user-images.githubusercontent.com/90393596/171995202-965b98e9-827e-4a48-8024-022d7e01f56b.png"> <img alt="Screen Shot 2022-06-04 at 18 38 41" width="92" src="https://user-images.githubusercontent.com/90393596/171995204-96761d9f-8761-4eb4-878e-d94d4aaf5450.png"> all these lines are connected to each other so should I disconnect them with a blank line
> 
> Doesn't matter

K
