### ISSUE TITLE
Pls pet support & auto Effect

### ISSUE THREAD

**Issue by kaanalp28** [didlly/grank#68]
**Pls pet support.**
Detects if the user has a pet. Buys if the buy option is enabled. Feeds, washes and plays automatically. Outputs when the pet will sleep and wake up.

**Auto Effect**

This is the option to use:

- Lucky horseshoe (Luck)
- Pizza (XP)
- Daily box (XP)
- Shredded Cheese (XP)
- Alcohol (Luck) !ONLY IF ROBBING IS ENABLED!

**End Interaction**

Automatically clicks to end interaction button if there is one. 
(No more grank errors because of an interaction not ending.)

**Comment by kaanalp28** [comment]
also there is an issue when the bot doesnt "End Interaction" with previous command, so the bot doesnt see the new commands, grank thinks its an error. Add a feature that ends interaction if there is an "End interaction" button in the response.

**Comment by Yoon0117** [comment]
Yeh I think the auto effect feature would be really nice since most cmds ate affected by those

**Comment by kaanalp28** [comment]
the end interaction thing is also important, that is probabşy the most important one

**Comment by sneazy-ibo** [comment]
> the end interaction thing is also important, that is probably the most important one

Didlly alr knows abt it bc there are other commands like pls stream and pls adv that already click the end interaction button

**Comment by didlly** [comment]
Grank automatically clicks on the `End Interaction` buttons, however Discord's backend is glitchy (yk those `Interaction failed` alerts you sometimes get when interacting with buttons), and so sometimes Grank fails to click on the button which causes a warning to be raised, which means Grank skips to the next command without clicking the End Interaction button. I have a [system](https://github.com/didlly/grank/blob/main/src/instance/Client.py#L830) in place to try and combat this but sometimes it fails as well.
