### ISSUE TITLE
Version For Android

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#69]
Sometimes people can't use a computer so it can be easier to use a phone for the program
https://github.com/MoleTheDev/DankMemer-Farmer
This guy made a version for Android and it works as same as the PC/Mac version
Is your code compatible for the Android version

**Comment by didlly** [comment]
Search Python for Android

**Comment by Yoon0117** [comment]
Sorry i didnt rly understand what you mean by that

**Comment by Sxvxgee** [comment]
> Sorry i didnt rly understand what you mean by that

Theres applications for running python scripts on android. Look them up in google play store.

**Comment by didlly** [comment]
> > Sorry i didnt rly understand what you mean by that
> 
> Theres applications for running python scripts on android. Look them up in google play store.

QPython 3L is the best in my opinion.

**Comment by Yoon0117** [comment]
> > Sorry i didnt rly understand what you mean by that
> 
> Theres applications for running python scripts on android. Look them up in google play store.

Ik that, I have Pydroid as my python on mobile. My question is, do I just run the program the same method as how I do with the Source Code?
Lastly I saw that whenever Grank is sending commands in the channel, I can't get into my discord mobile cause it says app crashed, unlike the web/app version of discord where you can just use discord normally while Grank is working

**Comment by didlly** [comment]
> > > Sorry i didnt rly understand what you mean by that
> > 
> > 
> > Theres applications for running python scripts on android. Look them up in google play store.
> 
> Ik that, I have Pydroid as my python on mobile. My question is, do I just run the program the same method as how I do with the Source Code? Lastly I saw that whenever Grank is sending commands in the channel, I can't get into my discord mobile cause it says app crashed, unlike the web/app version of discord where you can just use discord normally while Grank is working

Yes run it the same way. Ig your phone can't handle all the pings, like mine.

**Comment by Yoon0117** [comment]
> > > > Sorry i didnt rly understand what you mean by that
> > > 
> > > 
> > > Theres applications for running python scripts on android. Look them up in google play store.
> > 
> > 
> > Ik that, I have Pydroid as my python on mobile. My question is, do I just run the program the same method as how I do with the Source Code? Lastly I saw that whenever Grank is sending commands in the channel, I can't get into my discord mobile cause it says app crashed, unlike the web/app version of discord where you can just use discord normally while Grank is working
> 
> Yes run it the same way. Ig your phone can't handle all the pings, like mine.

Lol, its not because my phone's specs are bad
I think because there's some kinda error between my discord mobile client and the grank trying to login from another *device* sorta thing

**Comment by Sxvxgee** [comment]
> > > > > Sorry i didnt rly understand what you mean by that
> > > > 
> > > > 
> > > > Theres applications for running python scripts on android. Look them up in google play store.
> > > 
> > > 
> > > Ik that, I have Pydroid as my python on mobile. My question is, do I just run the program the same method as how I do with the Source Code? Lastly I saw that whenever Grank is sending commands in the channel, I can't get into my discord mobile cause it says app crashed, unlike the web/app version of discord where you can just use discord normally while Grank is working
> > 
> > Yes run it the same way. Ig your phone can't handle all the pings, like mine.
> 
> Lol, its not because my phone's specs are bad
> I think because there's some kinda error between my discord mobile client and the grank trying to login from another *device* sorta thing

Your phone sucks ass. That's why it crashes. Also your logic sucks ass as well. Grank uses the discord API, it has nothing to do with the client. Both the client on mobile and on web and desktop use the same API, yet no issue occurs. The fact that when you open discord while autofarming crashes your application has nothing to do with a "login from another device sorta thing"; it's that the pings are making discord use a little bit more resources that your shit phone can't handle, and thus it crashes.

**Comment by Yoon0117** [comment]
> > > > > > Sorry i didnt rly understand what you mean by that
> > > > > 
> > > > > 
> > > > > Theres applications for running python scripts on android. Look them up in google play store.
> > > > 
> > > > 
> > > > Ik that, I have Pydroid as my python on mobile. My question is, do I just run the program the same method as how I do with the Source Code? Lastly I saw that whenever Grank is sending commands in the channel, I can't get into my discord mobile cause it says app crashed, unlike the web/app version of discord where you can just use discord normally while Grank is working
> > > 
> > > 
> > > Yes run it the same way. Ig your phone can't handle all the pings, like mine.
> > 
> > 
> > Lol, its not because my phone's specs are bad
> > I think because there's some kinda error between my discord mobile client and the grank trying to login from another _device_ sorta thing
> 
> Your phone sucks ass. That's why it crashes. Also your logic sucks ass as well. Grank uses the discord API, it has nothing to do with the client. Both the client on mobile and on web and desktop use the same API, yet no issue occurs. The fact that when you open discord while autofarming crashes your application has nothing to do with a "login from another device sorta thing"; it's that the pings are making discord use a little bit more resources that your shit phone can't handle, and thus it crashes.

yes my logic my suck ass I dont really care about what you think about it / I use iPhone 12 so yeh im pretty sure it can handle a few ping don't you think / what's crashing is the discord app on my shitty emulator

**Comment by didlly** [comment]
> > > > > > > Sorry i didnt rly understand what you mean by that
> > > > > > 
> > > > > > 
> > > > > > Theres applications for running python scripts on android. Look them up in google play store.
> > > > > 
> > > > > 
> > > > > Ik that, I have Pydroid as my python on mobile. My question is, do I just run the program the same method as how I do with the Source Code? Lastly I saw that whenever Grank is sending commands in the channel, I can't get into my discord mobile cause it says app crashed, unlike the web/app version of discord where you can just use discord normally while Grank is working
> > > > 
> > > > 
> > > > Yes run it the same way. Ig your phone can't handle all the pings, like mine.
> > > 
> > > 
> > > Lol, its not because my phone's specs are bad
> > > I think because there's some kinda error between my discord mobile client and the grank trying to login from another _device_ sorta thing
> > 
> > 
> > Your phone sucks ass. That's why it crashes. Also your logic sucks ass as well. Grank uses the discord API, it has nothing to do with the client. Both the client on mobile and on web and desktop use the same API, yet no issue occurs. The fact that when you open discord while autofarming crashes your application has nothing to do with a "login from another device sorta thing"; it's that the pings are making discord use a little bit more resources that your shit phone can't handle, and thus it crashes.
> 
> yes my logic my suck ass I dont really care about what you think about it / I use iPhone 12 so yeh im pretty sure it can handle a few ping don't you think / what's crashing is the discord app on my shitty emulator

Personally, whenever I run Grank on an account and log into that account on my phone's discord my discord on my phone crashes cus my phone is old.

**Comment by Yoon0117** [comment]
Rip
I have a question what should I do here
![Screenshot_20220606-101339_Pydroid 3](https://user-images.githubusercontent.com/90393596/172079285-85bec0f4-a027-47f8-8478-941bcec7b494.jpg)

**Comment by didlly** [comment]
> Rip I have a question what should I do here ![Screenshot_20220606-101339_Pydroid 3](https://user-images.githubusercontent.com/90393596/172079285-85bec0f4-a027-47f8-8478-941bcec7b494.jpg)

What Pytohn version is that.

**Comment by sneazy-ibo** [comment]
> Sometimes people can't use a computer so it can be easier to use a phone for the program https://github.com/MoleTheDev/DankMemer-Farmer This guy made a version for Android and it works as same as the PC/Mac version Is your code compatible for the Android version

Host it on replit

**Comment by Yoon0117** [comment]
> > Rip I have a question what should I do here ![Screenshot_20220606-101339_Pydroid 3](https://user-images.githubusercontent.com/90393596/172079285-85bec0f4-a027-47f8-8478-941bcec7b494.jpg)
> 
> What Python version is that.

Oh wait, I just made a stupid mistake

**Comment by Yoon0117** [comment]
I accidentally put a bracket at the start of the code, which made the error.
