### ISSUE TITLE
Drop auto buyer

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#70]
Since Dank is dropping the drop items again, I kinda want to get them again, but since my time zone is different, I don't think I will be able to get the drops. So can you please make an auto drop buyer? I think this might be pretty useful

**Comment by Yoon0117** [comment]
Or can you please tell me how to make a custom command for sending a certain command like `pls buy per` at a certain time?

**Comment by sneazy-ibo** [comment]
> good idea, my time zone is also different, this would be very useful

It would be useful but drop events are pretty rare so that you only need this once or twice a month, I mean didlly could add this to grank but you can also manage to do this with custom commands if you setup the right timing or with a other simple selfbot

**Comment by didlly** [comment]
Can be handled with custom commands, and is not worth the time.

**Comment by Yoon0117** [comment]
> > good idea, my time zone is also different, this would be very useful
> 
> It would be useful but drop events are pretty rare so that you only need this once or twice a month, I mean didlly could add this to grank but you can also manage to do this with custom commands if you setup the right timing or with a other simple selfbot

is there any other selfbots you recommend?
