### ISSUE TITLE
v3.0.1 Bugs 

### ISSUE THREAD

**Issue by kaanalp28** [didlly/grank#71]
**Main opens visual studio code.**
I think it is no longer an .exe file, but .py file instead. When I try dragging to cmd, visual studio code continues to open.

**It checks if -pip is installed and up to date EVERY SINGLE TIME I open it.**
And yes, it is up to date now.

**There is no GRANK logo.**
The good ol' Grank logo is gone.

**Newest version.**
 I have the newest version (v3.0.1), but for some reason, the current_version file has v3.5 beta written in it.

**Expected behavior**
The same stratup to happen with previous versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/96485263/172169562-2488bc6a-6571-432b-bcdd-2c06ab3453e4.png)
![image](https://user-images.githubusercontent.com/96485263/172170477-c70733e4-d674-43c7-943c-9b1635e6b46d.png)
![image](https://user-images.githubusercontent.com/96485263/172170551-f8d7d1fa-7931-4e3e-92a8-8384167d898b.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: Mostly Google Chrome, sometimes Opera GX
 - Version: v3.0.1

**Additional context**
The problems above makes the startup very slow. Opening VS Code is slow, the -pip checks are slower.

**Comment by kaanalp28** [comment]
Also, where is the search & crime subcategories? There are no options to configure where to search.

![image](https://user-images.githubusercontent.com/96485263/172175368-c6e4cff6-b8aa-4ee2-aa08-aa77957bf9bd.png)

**Comment by didlly** [comment]
Invalid, please download the latest version from [here](https://github.com/didlly/grank/archive/refs/heads/main.zip). A lot of your files, like the current version file, config template file etc. are old. And the Grank logo is gone since PyPy fails to print ASCII art. Something related to this will be added to the user documentation soon.

**Comment by didlly** [comment]
> Also, where is the search & crime subcategories? There are no options to configure where to search.
> 
> ![image](https://user-images.githubusercontent.com/96485263/172175368-c6e4cff6-b8aa-4ee2-aa08-aa77957bf9bd.png)

Also that picture is of the cooldowns category.
