### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by Yoon0117** [didlly/grank#72]
![Screenshot_20220607-180838_Discord](https://user-images.githubusercontent.com/90393596/172343735-641c0280-1a0d-4286-a0f5-1e273db1abc8.jpg)
Not a big thing you don't have to do this
Grank only detects No Caps, but ignores Caps

**Comment by sneazy-ibo** [comment]
> Not a big thing you don't have to do this Grank only detects No Caps, but ignores Caps
That's how all bots work, you choose a prefix and the bot replies to it. If you have setup `grank` as prefix it will only reply to this one. Same goes for symbols, there is no Caps for them. Anyways one thing that didlly could add would be multiple prefixes

**Comment by didlly** [comment]
> > Not a big thing you don't have to do this Grank only detects No Caps, but ignores Caps
> > That's how all bots work, you choose a prefix and the bot replies to it. If you have setup `grank` as prefix it will only reply to this one. Same goes for symbols, there is no Caps for them. Anyways one thing that didlly could add would be multiple prefixes

Good idea.
