### ISSUE TITLE
Add feature where bot automatically stop when one of alt account blacklisted

### ISSUE THREAD

**Issue by blockcircuit** [didlly/grank#75]
Please add feature where all account will automatically stop if one of alt account detect by dankmemer or blacklisted, so other account were not blacklisted too.

**Comment by sneazy-ibo** [comment]
> Please add feature where all account will automatically stop if one of alt account detect by dankmemer or blacklisted, so other account were not blacklisted too.

Didlly could add this to the sc, but I don't rly think that it's rly nessesary aslong as you don't run grank for too long your accs should be safe, just use shifts and the antidetection features

**Comment by didlly** [comment]
https://github.com/didlly/grank/blob/main/src/instance/Client.py#L484

**Comment by blockcircuit** [comment]
amazing, I should try this!
